version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./app-php:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: .
        volumes:
            - ./app-php:/app
        networks:
            - code-network
    database:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'aggregator'
            MYSQL_PASSWORD: 'aggregator'
        volumes:
            - aggregator:/var/lib/mysql
        networks:
            - code-network
volumes:
    aggregator: 

networks:
    code-network:
