version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./app-php:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./app-php:/app
        networks:
            - code-network
    mysql:
    	image: mysql:latest
    	command: --default-authentication-plugin=mysql_native_password
    	restart: always
    	environment:
			MYSQL_ROOT_PASSWORD: example
			MYSQL_DATABASE: 'db'
			MYSQL_USER: 'app'
			MYSQL_PASSWORD: 'password'
			volumes:
				- my-db:/var/lib/mysql
volumes:
	my-db:
networks:
    code-network:
        driver: bridge
