CREATE DATABASE IF NOT EXISTS db;
USE db;

CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pages (
    pageId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    url VARCHAR(2083),
    title VARCHAR(255),
    type ENUM('SITE', 'RSS', 'SITEMAP', 'ATOM') NOT NULL DEFAULT 'SITE'
);

CREATE TABLE IF NOT EXISTS subscriptions (
    subId INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    userId INT NOT NULL, 
    pageId INT NOT NULL
--    FOREIGN KEY (userId) REFERENCES users(id),
--    FOREIGN KEY (pageId) REFERENCES pages(pageId)
);


CREATE TABLE IF NOT EXISTS webpages (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    url VARCHAR(2083),
    title VARCHAR(255),
    sourceId INT
--    FOREIGN KEY (sourceId) REFERENCES pages(pageId)
);

INSERT INTO pages (url, title, type) VALUES ('https://dbhattarai.info.np/sitemap.xml', 'dineshdb', 'SITEMAP');
INSERT INTO pages (url, title, type) VALUES ('https://atosh502.blogspot.com/sitemap.xml', 'atosh502', 'SITEMAP');
